name: CI - check index

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure index.html exists
        run: |
          if [ -f index.html ]; then
            echo "index.html found"
            wc -c index.html
          else
            echo "index.html not found" >&2
            exit 1
          fi
