
name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Optionally target a specific runner label you set on your EC2 runner (e.g., 'ec2')
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Apache Web Root
        run: |
          # Ensure Apache exists (safe if already installed)
          if ! command -v apache2 >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y apache2
            sudo systemctl enable apache2
            sudo systemctl start apache2
          fi

          # Clean old content
          sudo rm -rf /var/www/html/*

          # Copy repo contents (adjust if your site is in a subfolder)
          sudo cp -r ./* /var/www/html/

          # (Optional) Set correct ownership and perms for Apache to serve
          sudo chown -R www-data:www-data /var/www/html
          sudo find /var/www/html -type d -exec chmod 755 {} \;
          sudo find /var/www/html -type f -exec chmod 644 {} \;

          # (Optional) Restart Apache if needed
          sudo systemctl restart apache2
